package br.com.ufpb.dcx.si.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "PLACEHOLDER_ECOM_LIVRO_TABLE_NAME")

public class Livro{
    
    private String idLivro;

    
/**
* Title.
*/
    private String title;

/**
* Author.
*/
    private String author;

/**
* Edition.
*/
    private Integer edition;


    public Livro(){
    // TODO Auto-generated constructor stub
    }

    @DynamoDBHashKey(attributeName="idlivro")
    
    @DynamoDBAutoGeneratedKey 
    public String getIdLivro(){
        return this.idLivro;
    }

    public void setIdLivro(String idLivro){
        this.idLivro=idLivro;
    }

        /**
    * Gets the title.
    *
    * @return title.
    */
    @DynamoDBAttribute(attributeName = "title")
    public String getTitle() {
        return title;
    }
    /**
    * Gets the author.
    *
    * @return author.
    */
    @DynamoDBAttribute(attributeName = "author")
    public String getAuthor() {
        return author;
    }
    /**
    * Gets the edition.
    *
    * @return edition.
    */
    @DynamoDBAttribute(attributeName = "edition")
    public Integer getEdition() {
        return edition;
    }

    
        /**
    * Sets the title.
    *
    * @param name title.
    */
    public void setTitle(String title) {
        this.title = title;
    }
    /**
    * Sets the author.
    *
    * @param name author.
    */
    public void setAuthor(String author) {
        this.author = author;
    }
    /**
    * Sets the edition.
    *
    * @param name edition.
    */
    public void setEdition(Integer edition) {
        this.edition = edition;
    }


    public String toString(){
        
        return null;
        /*
         * for example:
         * return String.format("Entity [id=%s, name=%s, price=$%f]", this.id, this.name, this.price);
         */
    }
}